# Generated by Django 5.2 on 2025-05-08 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios_ti', '0002_recolectoinventario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacionservicio',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('finalizado', 'Finalizado')], default='pendiente', max_length=20),
        ),
    ]
